export const rowData = [
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" },
    { value: "0" }
  ];
  export const ColsCkSts = [
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false },
    { checked:false }
  ];
 